import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import WalletProvider from "../../WalletProvider";
import Header from "@/components/shared/Header";

import { Toaster } from "react-hot-toast";

import { StateManagementProvider } from "../../StateManagement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <WalletProvider>

          <StateManagementProvider>

            <Header/>

              {children}

           </StateManagementProvider>
          <Toaster/>

        </WalletProvider>

        
        
        </body>
    </html>
  );
}
